<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['configuration_backup_app_description'] = 'The configuration backup and restore app allows an administrator to take a snapshot (archive file) of all configuration settings of the system, allowing easy restoration in the event data is lost.';
$lang['configuration_backup_app_name'] = 'Настройка Бэкапов';
$lang['configuration_backup_archives'] = 'Архивы';
$lang['configuration_backup_backup_file_invalid'] = 'Резервное имя файла - инвалид.';
$lang['configuration_backup_backup_now'] = 'Резервное копирование сейчас';
$lang['configuration_backup_checking_version'] = 'Проверка архива на совместимость с версией';
$lang['configuration_backup_clear'] = 'Очистить';
$lang['configuration_backup_confirm_restore'] = 'Вы уверены, что хотите восстановиться с помощью следующего архивного файла?';
$lang['configuration_backup_directory_could_not_be_converted'] = 'Каталог не может быть преобразован.';
$lang['configuration_backup_download_and_intstall_apps'] = 'Загрузка и установка приложений.';
$lang['configuration_backup_importing_ldap'] = 'Импорт каталога LDAP';
$lang['configuration_backup_not_registered'] = 'Ваша система должна быть зарегистрирована прежде, чем восстанавливать параметры конфигурации.';
$lang['configuration_backup_older_version_warn'] = 'Более старая версия резервного копирования не делает установку приложений - пожалуйста, установите необходимые приложения из Рынка после восстановления';
$lang['configuration_backup_release_mismatch'] = 'Информация о версии в файле резервной копии не совпадает с версией, установленной на этой системе.';
$lang['configuration_backup_release_missing'] = 'Информация о версии не доступна в файле резервной копии.';
$lang['configuration_backup_restarting_service:'] = 'Перезапуск служб:';
$lang['configuration_backup_restore_already_in_progress'] = 'Восстановление в процессе.';
$lang['configuration_backup_restore_complete'] = 'Восстановление завершено.';
$lang['configuration_backup_restore_file'] = 'Файл архива';
$lang['configuration_backup_restore_from_archive'] = 'Восстановление из архива';
$lang['configuration_backup_restore_log'] = 'Восстановление журнала';
$lang['configuration_backup_starting_event_system'] = 'Starting event monitor service';
$lang['configuration_backup_status_data_not_available'] = 'Информация о статусе не доступна.';
$lang['configuration_backup_stopping_event_system'] = 'Stopping event monitor service';
$lang['configuration_backup_unable_to_start_restore'] = 'Не удалось запустить операцию восстановления';
$lang['configuration_backup_unpacking_archive'] = 'Распаковка архивного файла';
$lang['configuration_backup_waiting_for_software_updates_system'] = 'Ожидайте программное обеспечение обновляет систему';
$lang['configuration_backup_yum_busy'] = 'Диспетчер пакетов занят.';
