#!/bin/sh

# Add sudoers entries
#--------------------

/usr/sbin/addsudo /bin/tar app-configuration-backup
/usr/sbin/addsudo /usr/sbin/configuration-restore app-configuration-backup

# Fix truncated backup archive filenames from an older release
ARCHIVES=$(find /var/clearos/configuration_backup -name '*.tgz' |\
    egrep -v '^.*backup-.*-([0-9]{2})-([0-9]{2})-([0-9]{4})-([0-9]{2})-([0-9]{2})-([0-9]{2}).tgz')
H=0; M=0; S=0
for ARCHIVE in $ARCHIVES; do
    PREFIX=$(echo $ARCHIVE | sed -e 's/^\(.*\)backup.*$/\1backup/')
    PARTS=$(echo $ARCHIVE | sed -e 's/.*backup-\(.*\)-\([0-9]*\)-\([0-9]*-[0-9]*\)\.tgz$/\1:\3-\2/')
    HOSTID=$(echo $PARTS | cut -d: -f1)
    DATETIME=$(echo $PARTS | cut -d: -f2)

    FORMAT="$PREFIX-$HOSTID-$DATETIME-%02d-%02d-%02d.tgz"

    mv "$ARCHIVE" "$(printf $FORMAT $H $M $S)"

    S=$[ $S + 1];
    if [ $S -eq 60 ]; then S=0; M=$[ $M + 1 ]; fi
    if [ $M -eq 60 ]; then M=0; H=$[ $H + 1 ]; fi
done
