#!/bin/sh

# Add sudoers entries
#--------------------

/usr/sbin/addsudo /bin/tar app-configuration-backup
/usr/sbin/addsudo /usr/sbin/configuration-restore app-configuration-backup

# FIXME: remove any time after 6.4.0 release
chmod 777 /var/clearos/framework/tmp ; chmod +t /var/clearos/framework/tmp

# Fix truncated backup archive filenames from an older release
ARCHIVES=$(find /var/clearos/configuration_backup -name '*.tgz' |\
        egrep -v '^.*backup-.*-([0-9]{2})-([0-9]{2})-([0-9]{4})-([0-9]{2})-([0-9]{2})-([0-9]{2}).tgz')
H=0; M=0; S=0
for ARCHIVE in $ARCHIVES; do
        FORMAT=$(echo $ARCHIVE | sed -e 's/\(.*\)\.tgz$/\1-%02d-%02d-%02d.tgz/')
        mv "$ARCHIVE" $(printf "$FORMAT" $H $M $S)
        S=$[ $S + 1];
        if [ $S -eq 60 ]; then S=0; M=$[ $M + 1 ]; fi
        if [ $M -eq 60 ]; then M=0; H=$[ $H + 1 ]; fi
done

