<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['configuration_backup_app_description'] = 'Aplikacja kopii zapasowej i przywracania konfiguracji  pozwala administratorowi na zrobienie migawki całej konfiguracji systemu, umożliwiając łatwe przywrócenia danych w przypadku ich utraty.';
$lang['configuration_backup_app_name'] = 'Configuration Backup and Restore';
$lang['configuration_backup_archives'] = 'Archiwa';
$lang['configuration_backup_backup_file_invalid'] = 'Nazwa pliku kopii zapasowej jest nieprawidłowa.';
$lang['configuration_backup_backup_now'] = 'Utwórz kopię';
$lang['configuration_backup_checking_version'] = 'Sprawdzanie kompatybilności wersji archiwum';
$lang['configuration_backup_clear'] = 'Wyczyść';
$lang['configuration_backup_confirm_restore'] = 'Czy jesteś pewien, że chcesz przywrócić dane używając następującego pliku archiwizacji?';
$lang['configuration_backup_directory_could_not_be_converted'] = 'Folder nie mógł być zmieniony.';
$lang['configuration_backup_download_and_intstall_apps'] = 'Pobieranie i instalowanie aplikacji.';
$lang['configuration_backup_importing_ldap'] = 'Importowanie katalogu LDAP';
$lang['configuration_backup_not_registered'] = 'Twój system musi zostać zarejestrowany przed przywróceniem ustawień konfiguracyjnych.';
$lang['configuration_backup_older_version_warn'] = 'Starsze wersje nie zawierają pliku manifestu instalacji aplikacji - proszę zainstalować wymagane aplikacje ze sklepu po przywróceniu danych';
$lang['configuration_backup_release_mismatch'] = 'Informacja o wersji w kopii zapasowej nie zgadza się z wersją zainstalowaną na tym systemie.';
$lang['configuration_backup_release_missing'] = 'Informacja o wersji nie jest dostępna w pliku kopii zapasowej.';
$lang['configuration_backup_restarting_service:'] = 'Uruchamianie ponowne usługi:';
$lang['configuration_backup_restore_already_in_progress'] = 'Przywracanie danych w toku.';
$lang['configuration_backup_restore_complete'] = 'Przywracanie danych zakończone.';
$lang['configuration_backup_restore_file'] = 'Plik archiwum';
$lang['configuration_backup_restore_from_archive'] = 'Przywróć dane z archiwum';
$lang['configuration_backup_restore_log'] = 'Log z przywracania danych';
$lang['configuration_backup_starting_event_system'] = 'Uruchamianie usługi monitora zdażeń';
$lang['configuration_backup_status_data_not_available'] = 'Dane o stanie nie są dostępne.';
$lang['configuration_backup_stopping_event_system'] = 'Zatrzymywanie usługi monitora zdarzeń';
$lang['configuration_backup_unable_to_start_restore'] = 'Nie można uruchomić operacji przywracania danych';
$lang['configuration_backup_unpacking_archive'] = 'Wypakowywanie pliku archiwum';
$lang['configuration_backup_waiting_for_software_updates_system'] = 'Oczekiwanie na system aktualizacji oprogramowania';
$lang['configuration_backup_yum_busy'] = 'Manager oprogramowanie jest zajęty.';
